#!/bin/bash

# file names
OUTPUT_FNAME=data/file_list.txt
TEMP_FNAME=temp.txt

# initialize output file
rm -f $OUTPUT_FNAME
touch $OUTPUT_FNAME

# get pubmed files
WEBSITE=https://ftp.ncbi.nlm.nih.gov/pubmed/
for PAGE in baseline updatefiles; do
    wget -O $TEMP_FNAME -k $WEBSITE$PAGE/ &> /dev/null
    grep -oE "$WEBSITE$PAGE/[^.]+.xml.gz" $TEMP_FNAME >> $OUTPUT_FNAME
    rm $TEMP_FNAME
done

# remove duplicates
sort -u $OUTPUT_FNAME -o $OUTPUT_FNAME
