name: Update Databases

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  update-pubmed:
    runs-on: ubuntu-latest
    environment: actions
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
          python-version: 3.9
    - name: Create .ezazure file
      env:
        EZAZURE_TOKEN: ${{ secrets.EZAZURE_TOKEN }}
      run: |
        echo "connection_str: $EZAZURE_TOKEN" > .ezazure
        echo "container: data" >> .ezazure
    - name: Setup python environment
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Download most recent file list
      run: |
        cmd/get-files
    - name: Download database
      run: |
        python -m ezazure --download data/pubmed.db
    - name: Update database
      run: |
        python litai/db.py --append
    - name: Upload database
      run: |
        python -m ezazure --upload data/pubmed.db

  update-tables:
    needs: update-pubmed
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TABLE_NAME: ['hbot', 'senescence']
    environment: actions
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
          python-version: 3.9
    - name: Create .ezazure file
      env:
        EZAZURE_TOKEN: ${{ secrets.EZAZURE_TOKEN }}
      run: |
        echo "connection_str: $EZAZURE_TOKEN" > .ezazure
        echo "container: data" >> .ezazure
    - name: Setup python environment
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Download database and pmids
      run: |
        python -m ezazure --download data/pubmed.db
        python -m ezazure --download data/senescence_pmids.txt
    - name: Update table
      env:
        TABLE_NAME: ${{ matrix.TABLE_NAME }}
      run: |
        python litai/score.py config/$TABLE_NAME.yaml
    - name: Upload table
      env:
        TABLE_NAME: ${{ matrix.TABLE_NAME }}
      run: |
        python -m ezazure --upload data/$TABLE_NAME.db

  update-image:
    needs: update-tables
    runs-on: ubuntu-latest
    environment: actions
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Create .ezazure file
      env:
        EZAZURE_TOKEN: ${{ secrets.EZAZURE_TOKEN }}
      run: |
        echo "connection_str: $EZAZURE_TOKEN" > .ezazure
        echo "container: data" >> .ezazure
    - name: Download tables
      run: |
        python -m ezazure --download data/hbot.db
        python -m ezazure --download data/senescence.db
    - name: Create and upload docker image
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        . cmd/docker --upload
    - name: Update website
      run: |
        python -m ezazure --upload --regex "html/.*" --container app
